version: "3"
services:
  mariadb:
    image: mariadb
    build: requirements/mariadb
    container_name: mariadb
    ports:
      - "3306"
    volumes:
        - wp-db:/var/lib/mysql/wordpress
    networks:
      - mynetwork
    env_file:
      - .env
    restart: always
  wordpress:
    image: wordpress
    build: requirements/wordpress
    container_name: wordpress
    ports:
      - "9000"
    volumes:
        - wp-files:/var/www/html
    depends_on:
      - mariadb
    env_file:
      - .env
    restart: always
    networks:
      - mynetwork
  nginx:
    image: nginx
    build: requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
        - wp-files:/var/www/html
    depends_on:
      - mariadb
      - wordpress
    restart: always
    networks:
      - mynetwork
volumes:
  wp-db:
    driver_opts:
      type: none
      device: /home/ynoam/data/wp-db
      o: bind
  wp-files:
    driver_opts:
      type: none
      device: /home/ynoam/data/wp-files
      o: bind

networks:
  mynetwork: