version: '3'
services:
  mariadb:
    build:
      context: requirements/mariadb
    container_name: mariadb
    volumes:
      - dbdata:/var/lib/mysql
    restart: always
    networks:
      - mynetwork
  wordpress:
    build:
      context: requirements/wordpress
    container_name: wordpress
    volumes:
      - wordpress:/wordpress
    depends_on:
      - mariadb
    restart: always
    networks:
      - mynetwork
  nginx:
    build:
      context: requirements/nginx
    container_name: nginx
    ports:
      - 443:443
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - mariadb
      - wordpress
    restart: always
    networks:
      - mynetwork
volumes:
  wordpress:
  dbdata:
networks:
  mynetwork:
    driver: bridge